name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Build with dotnet
      working-directory: ./SMTP.Impostor.Worker
      run: dotnet build --configuration Release
