/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  HubStatus,
  IHubMessage,
  IHubSocketProvider,
} from './impostor-hub/model';

export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface ImpostorHub {
    'connectAsync': (url?: string) => Promise<void>;
    'disconnectAsync': () => Promise<void>;
    'sendAsync': (message: IHubMessage) => Promise<void>;
    'socketProvider': IHubSocketProvider;
    'status': HubStatus;
    'url': string;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLImpostorHubElement extends Components.ImpostorHub, HTMLStencilElement {}
  var HTMLImpostorHubElement: {
    prototype: HTMLImpostorHubElement;
    new (): HTMLImpostorHubElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'impostor-hub': HTMLImpostorHubElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppRoot {}
  interface ImpostorHub {
    'onMessageReceived'?: (event: CustomEvent<IHubMessage>) => void;
    'onStatusChanged'?: (event: CustomEvent<HubStatus>) => void;
    'socketProvider'?: IHubSocketProvider;
    'status'?: HubStatus;
    'url'?: string;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'impostor-hub': ImpostorHub;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'impostor-hub': LocalJSX.ImpostorHub & JSXBase.HTMLAttributes<HTMLImpostorHubElement>;
    }
  }
}


